@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package nl.melonstudios.bmnw.particle;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;